### ISSUE TITLE
CTest Failures

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITKSphinxExamples#349]
Two CTests are failing:

[CDash results](https://open.cdash.org/viewTest.php?onlyfailed&buildid=7888816)

```
Traceback (most recent call last):
  File "/home/runner/work/bld/itkpython/lib/python3.8/site-packages/itk/support/template_class.py", line 525, in __getitem__
    this_item = self.__template__[key]
KeyError: (<class 'itk.itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4Python.itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSF2'>,)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/Ex/src/Registration/Metricsv4/RegisterTwoPointSets/Code.py", line 164, in <module>
    test_registration(dimension)
  File "/home/runner/work/Ex/src/Registration/Metricsv4/RegisterTwoPointSets/Code.py", line 72, in test_registration
    ShiftScalesType = itk.RegistrationParameterScalesFromPhysicalShift[
  File "/home/runner/work/bld/itkpython/lib/python3.8/site-packages/itk/support/template_class.py", line 529, in __getitem__
    raise itk.TemplateTypeError(self, key)
itk.support.extras.TemplateTypeError: itk.RegistrationParameterScalesFromPhysicalShift is not wrapped for input type `itk.JensenHavrdaCharvatTsallisPointSetToPointSetMetricv4[itk.PointSet[itk.F,2]]`.
```

Failures may be related to recent changes in wrapping for `itk::RegistrationParameterScalesFromPhysicalShift`:
[https://github.com/InsightSoftwareConsortium/ITK/commit/6310d36d351386b90f94ca495da3c89f99fd16ab](https://github.com/InsightSoftwareConsortium/ITK/commit/6310d36d351386b90f94ca495da3c89f99fd16ab)

**Comment by tbirdso** [comment]
`RegisterTwoPointSetsTest2DPython` and `RegisterTwoPointSetsTest3DPython` rely on ITK Python PyPI packages for dashboard results and are still failing because the changes in [https://github.com/InsightSoftwareConsortium/ITK/pull/3406](https://github.com/InsightSoftwareConsortium/ITK/pull/3406) have not been released in an ITK Python package yet. Tests are disabled for now and should be revisited once itk>v5.3rc04 is released.
